# yaml-language-server: $schema=<https://uniform.app/schemas/json-schema/component-definition/v1.json>
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productTileGrid
name: Product Tile Grid
icon: display-grid
parameters:
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig: null
categoryId: 4e552690-edb9-47a0-8a71-d5752a28365b
previewImageUrl: >-
  https://res.cloudinary.com/uniform-demos/image/upload/v1699752392/dsuo4vdwfypaaqcb5eib.png
useTeamPermissions: true
slots:
  - id: tiles
    name: Tiles
    allowedComponents:
      - $test
      - $loop
      - $personalization
      - $p:40c7b179-7fb8-46e7-8f2c-5005b9e6b4cb
    allowAllComponents: false
    inheritAllowedComponents: false
    patternsInAllowedComponents: true
titleParameter: title
canBeComposition: false
created: '2023-11-15T14:57:33.454376+00:00'
updated: '2023-11-19T01:03:09.387589+00:00'
variants:
  - id: carousel
    name: Carousel
